import { NextResponse } from 'next/server';
import { ResumeData } from '@/types/resume';
import { COMPRESS_STAGE_1, COMPRESS_STAGE_2, COMPRESS_STAGE_3 } from '@/templates/utils';
import { generateHarvardHtml } from '@/templates/harvard';
import { generateStanfordHtml } from '@/templates/stanford';
import { generateModernHtml } from '@/templates/modern';
import { generateCompactHtml } from '@/templates/compact';
import { generateExecutiveHtml } from '@/templates/executive';
import { generateMinimalDividerHtml } from '@/templates/minimal-divider';
import { generateAcademicHtml } from '@/templates/academic';
import { generateAtsLightHtml } from '@/templates/ats-light';
import { getSession } from '@/lib/auth/jwt';
import { checkUserAccess } from '@/lib/access';

// Trigger re-build with fixed ESLint types
export const runtime = 'nodejs';

function selectTemplate(resumeData: ResumeData, template: string): string {
    switch (template) {
        case 'harvard': return generateHarvardHtml(resumeData);
        case 'stanford': return generateStanfordHtml(resumeData);
        case 'modern': return generateModernHtml(resumeData);
        case 'compact': return generateCompactHtml(resumeData);
        case 'executive': return generateExecutiveHtml(resumeData);
        case 'minimal-divider': return generateMinimalDividerHtml(resumeData);
        case 'academic': return generateAcademicHtml(resumeData);
        case 'ats-light': return generateAtsLightHtml(resumeData);
        default: return generateHarvardHtml(resumeData);
    }
}

async function injectCss(page: import('puppeteer').Page, css: string): Promise<void> {
    await page.evaluate((cssText: string) => {
        document.querySelectorAll('style[data-compress]').forEach(el => el.remove());
        const s = document.createElement('style');
        s.setAttribute('data-compress', 'true');
        s.textContent = cssText;
        document.head.appendChild(s);
    }, css);
}

async function injectWatermark(page: import('puppeteer').Page): Promise<void> {
    await page.evaluate(() => {
        // Remove existing watermark if any
        document.querySelectorAll('#resumeforge-watermark').forEach(el => el.remove());

        const wm = document.createElement('div');
        wm.id = 'resumeforge-watermark';
        wm.style.cssText = `
            position: fixed;
            top: 0; left: 0; right: 0; bottom: 0;
            pointer-events: none;
            z-index: 9999;
            overflow: hidden;
        `;

        // Generate a grid of diagonal watermark text across the entire page
        const text = 'Generated by ResumeForgeAI – Upgrade to remove watermark';
        let html = '';
        for (let row = -2; row < 20; row++) {
            for (let col = -2; col < 6; col++) {
                const top = row * 160 + col * 50;
                const left = col * 320 - 80;
                html += `<div style="
                    position: absolute;
                    top: ${top}px;
                    left: ${left}px;
                    transform: rotate(-35deg);
                    transform-origin: left top;
                    white-space: nowrap;
                    font-size: 13px;
                    font-family: Arial, sans-serif;
                    color: rgba(0,0,0,0.09);
                    font-weight: 600;
                    letter-spacing: 0.5px;
                    user-select: none;
                ">${text}</div>`;
            }
        }
        wm.innerHTML = html;
        document.body.appendChild(wm);
    });
}

async function getOverflowRatio(page: import('puppeteer').Page): Promise<number> {
    return page.evaluate(() => {
        const A4_CONTENT_H = 1050;
        return document.body.scrollHeight / A4_CONTENT_H;
    });
}

export async function POST(request: Request) {
    let browser: import('puppeteer').Browser | null = null;
    try {
        const body = await request.json();
        const resumeData: ResumeData = body.resumeData;
        const template: string = body.template || 'harvard';

        console.log(`[Download] Starting PDF generation for template: ${template}`);

        if (!resumeData) {
            return NextResponse.json({ error: 'No resume data provided' }, { status: 400 });
        }

        // ── Access check (server-side, no frontend trust) ──────────────────────
        const session = await getSession();
        let showWatermark = true;

        if (session?.userId) {
            const access = await checkUserAccess(session.userId);
            showWatermark = !access.hasAccess;
            console.log(`[Download] userId=${session.userId} access=${access.reason} watermark=${showWatermark}`);
        } else {
            console.log('[Download] No session — applying watermark');
        }
        // ──────────────────────────────────────────────────────────────────────

        const html = selectTemplate(resumeData, template);

        const puppeteer = await import('puppeteer');
        browser = await puppeteer.default.launch({
            headless: true,
            args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
        });

        const page = await browser.newPage();
        await page.setViewport({ width: 794, height: 1122, deviceScaleFactor: 1 });
        await page.setContent(html, { waitUntil: 'domcontentloaded' });

        // ── Iterative 3-stage compression ───────────────────────────────────────
        let ratio = await getOverflowRatio(page);
        console.log(`[Download] template="${template}" initial ratio=${ratio.toFixed(3)}`);

        if (ratio > 1) {
            await injectCss(page, COMPRESS_STAGE_1);
            ratio = await getOverflowRatio(page);
        }
        if (ratio > 1) {
            await injectCss(page, COMPRESS_STAGE_2);
            ratio = await getOverflowRatio(page);
        }
        if (ratio > 1) {
            await injectCss(page, COMPRESS_STAGE_3);
            ratio = await getOverflowRatio(page);
        }
        // ────────────────────────────────────────────────────────────────────────

        // ── Inject watermark AFTER compression (preserves layout) ───────────────
        console.log(`[Download] Injecting watermark: ${showWatermark}`);
        if (showWatermark) {
            await injectWatermark(page);
        }

        console.log('[Download] Generating PDF buffer...');
        const pdfBuffer = await page.pdf({
            format: 'A4',
            printBackground: true,
            preferCSSPageSize: true,
            pageRanges: '1',
        });
        console.log(`[Download] Done. Buffer size=${pdfBuffer.length} bytes`);

        return new NextResponse(Buffer.from(pdfBuffer), {
            status: 200,
            headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': 'attachment; filename="resume.pdf"',
                'X-Compress-Ratio': ratio.toFixed(3),
                'X-Watermark': showWatermark ? 'true' : 'false',
                'Cache-Control': 'no-store, max-age=0',
            },
        });

    } catch (e: unknown) {
        console.error('[Download] CRITICAL PDF Error:', e);
        const error = e as Error;
        return NextResponse.json(
            {
                error: 'PDF generation failed',
                details: error.message || String(e),
                stack: process.env.NODE_ENV === 'development' ? error.stack : undefined
            },
            { status: 500 }
        );
    } finally {
        if (browser) {
            console.log('[Download] Closing browser instance');
            await browser.close();
        }
    }
}
