import { NextResponse } from 'next/server';
import { ResumeData } from '@/types/resume';
import { generateHarvardHtml } from '@/templates/harvard';
import { generateStanfordHtml } from '@/templates/stanford';
import { generateModernHtml } from '@/templates/modern';
import { generateCompactHtml } from '@/templates/compact';
import { generateExecutiveHtml } from '@/templates/executive';
import { generateMinimalDividerHtml } from '@/templates/minimal-divider';
import { generateAcademicHtml } from '@/templates/academic';
import { generateAtsLightHtml } from '@/templates/ats-light';
import { getSession } from '@/lib/auth/jwt';
import { checkUserAccess } from '@/lib/access';
import { logPDFDownload } from '@/lib/admin-logger';
import puppeteer, { Browser, Page } from 'puppeteer-core';
import chromium from '@sparticuz/chromium';

// Trigger re-build with fixed ESLint types
export const runtime = 'nodejs';

function selectTemplate(resumeData: ResumeData, template: string): string {
    switch (template) {
        case 'harvard': return generateHarvardHtml(resumeData);
        case 'stanford': return generateStanfordHtml(resumeData);
        case 'modern': return generateModernHtml(resumeData);
        case 'compact': return generateCompactHtml(resumeData);
        case 'executive': return generateExecutiveHtml(resumeData);
        case 'minimal-divider': return generateMinimalDividerHtml(resumeData);
        case 'academic': return generateAcademicHtml(resumeData);
        case 'ats-light': return generateAtsLightHtml(resumeData);
        default: return generateHarvardHtml(resumeData);
    }
}



async function injectWatermark(page: Page): Promise<void> {
    await page.evaluate(() => {
        // Remove existing watermark if any
        document.querySelectorAll('#resumeforge-watermark').forEach(el => el.remove());

        const wm = document.createElement('div');
        wm.id = 'resumeforge-watermark';
        wm.style.cssText = `
            position: fixed;
            top: 0; left: 0; right: 0; bottom: 0;
            pointer-events: none;
            z-index: 9999;
            overflow: hidden;
        `;

        // Generate a grid of diagonal watermark text across the entire page
        const text = 'Generated by ResumeForgeAI – Upgrade to remove watermark';
        let html = '';
        for (let row = -2; row < 20; row++) {
            for (let col = -2; col < 6; col++) {
                const top = row * 160 + col * 50;
                const left = col * 320 - 80;
                html += `<div style="
                    position: absolute;
                    top: ${top}px;
                    left: ${left}px;
                    transform: rotate(-35deg);
                    transform-origin: left top;
                    white-space: nowrap;
                    font-size: 13px;
                    font-family: Arial, sans-serif;
                    color: rgba(0,0,0,0.09);
                    font-weight: 600;
                    letter-spacing: 0.5px;
                    user-select: none;
                ">${text}</div>`;
            }
        }
        wm.innerHTML = html;
        document.body.appendChild(wm);
    });
}

async function getOverflowRatio(page: Page): Promise<number> {
    return page.evaluate(() => {
        const A4_CONTENT_H = 1050;
        return document.body.scrollHeight / A4_CONTENT_H;
    });
}

export async function POST(request: Request) {
    let browser: Browser | null = null;
    try {
        const body = await request.json();
        const resumeData: ResumeData = body.resumeData;
        const template: string = body.template || 'harvard';

        console.log(`[Download] Starting PDF generation for template: ${template}`);

        if (!resumeData) {
            return NextResponse.json({ error: 'No resume data provided' }, { status: 400 });
        }

        // ── Access check (server-side, no frontend trust) ──────────────────────
        const session = await getSession();
        let showWatermark = true;

        if (session?.userId) {
            const access = await checkUserAccess(session.userId);
            showWatermark = !access.hasAccess;
            console.log(`[Download] userId=${session.userId} access=${access.reason} watermark=${showWatermark}`);
        } else {
            console.log('[Download] No session — applying watermark');
        }
        // ──────────────────────────────────────────────────────────────────────

        const html = selectTemplate(resumeData, template);

        // ── 1. PDF Generation logic for Production/Local ──
        const isLocal = process.env.NODE_ENV === 'development' || !process.env.VERCEL;

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const c = chromium as any;

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        let launchOptions: any;

        if (isLocal) {
            launchOptions = {
                args: [],
                executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
                headless: true,
            };
        } else {
            // Updated Vercel configuration for @sparticuz/chromium 123+
            launchOptions = {
                args: c.args,
                defaultViewport: c.defaultViewport,
                executablePath: await c.executablePath(),
                headless: c.headless,
            };
        }

        browser = await puppeteer.launch(launchOptions);

        const page = await browser.newPage();
        await page.setContent(html, { waitUntil: 'networkidle0' });

        const ratio = await getOverflowRatio(page);

        // ── 2. Inject watermark if needed ──
        if (showWatermark) {
            await injectWatermark(page);
        }

        console.log('[Download] Generating PDF buffer...');
        const pdfBuffer = await page.pdf({
            format: 'A4',
            printBackground: true,
        });
        console.log(`[Download] Done. Buffer size=${pdfBuffer.length} bytes`);

        // Fire-and-forget admin log
        if (session?.userId) {
            logPDFDownload({
                userId: session.userId,
                resumeName: (resumeData as unknown as Record<string, unknown>)?.name as string || 'Untitled',
                template,
                watermarked: showWatermark
            });
        }

        return new NextResponse(Buffer.from(pdfBuffer), {
            status: 200,
            headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': 'attachment; filename="resume.pdf"',
                'X-Compress-Ratio': ratio.toFixed(3),
                'X-Watermark': showWatermark ? 'true' : 'false',
                'Cache-Control': 'no-store, max-age=0',
            },
        });

    } catch (e: unknown) {
        console.error('[Download] CRITICAL PDF Error:', e);
        const error = e as Error;
        return NextResponse.json(
            {
                error: 'PDF generation failed',
                details: error.message || String(e),
                stack: process.env.NODE_ENV === 'development' ? error.stack : undefined
            },
            { status: 500 }
        );
    } finally {
        if (browser) {
            console.log('[Download] Closing browser instance');
            await browser.close();
        }
    }
}
