export const dynamic = 'force-dynamic';
import { NextResponse } from 'next/server';
import { ResumeData } from '@/types/resume';
import { renderResumeToHtml } from '@/lib/resume-server-renderer';
import { getSession } from '@/lib/auth/jwt';
import { checkUserAccess } from '@/lib/access';
import { logPDFDownload } from '@/lib/admin-logger';
import { incrementForgeUsage } from '@/lib/auth/usage';
import puppeteer, { Browser, Page } from 'puppeteer-core';
import chromium from '@sparticuz/chromium';
import fs from 'fs';
import path from 'path';

async function injectWatermark(page: Page): Promise<void> {
    await page.evaluate(() => {
        document.querySelectorAll('#resumeforge-watermark').forEach(el => el.remove());
        const wm = document.createElement('div');
        wm.id = 'resumeforge-watermark';
        wm.style.cssText = 'position: fixed; top: 0; left: 0; right: 0; bottom: 0; pointer-events: none; z-index: 9999; overflow: hidden;';
        const text = 'Generated by ResumeForgeAI – Upgrade to remove watermark';
        let html = '';
        for (let row = -2; row < 20; row++) {
            for (let col = -2; col < 6; col++) {
                const top = row * 160 + col * 50;
                const left = col * 320 - 80;
                html += `<div style="position: absolute; top: ${top}px; left: ${left}px; transform: rotate(-35deg); transform-origin: left top; white-space: nowrap; font-size: 13px; font-family: Arial, sans-serif; color: rgba(0,0,0,0.09); font-weight: 600; letter-spacing: 0.5px; user-select: none;">${text}</div>`;
            }
        }
        wm.innerHTML = html;
        document.body.appendChild(wm);
    });
}

export async function POST(request: Request) {
    let browser: Browser | null = null;
    let session: { userId?: string } | null = null;
    let showWatermark = true;

    try {
        // 1. Get session EARLY to avoid "cookies called outside request scope" errors
        try {
            session = await getSession();
            if (session?.userId) {
                const access = await checkUserAccess(session.userId);
                showWatermark = !access.hasAccess;
            }
        } catch (authErr) {
            console.error('[Download] Auth/Access check failed:', authErr);
        }

        // 2. Parse request body
        let body: { resumeData: ResumeData; template?: string };
        try {
            body = await request.clone().json().catch(async () => {
                const text = await request.text();
                return JSON.parse(text);
            });
        } catch (jsonErr) {
            console.error('[Download] Request body parsing failed:', jsonErr);
            return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
        }

        const resumeData: ResumeData = body.resumeData;
        const template: string = body.template || 'harvard';

        if (!resumeData) {
            return NextResponse.json({ error: 'No resume data provided' }, { status: 400 });
        }

        console.log(`[Download] PDF gen start | Template: ${template} | Watermark: ${showWatermark}`);

        const html = renderResumeToHtml(resumeData, template);
        const isLocal = process.env.NODE_ENV === 'development' || !process.env.VERCEL;
        const c = (chromium as unknown) as { args: string[]; defaultViewport: unknown; executablePath: () => Promise<string>; headless: boolean };
        let launchOptions: unknown;

        if (isLocal) {
            launchOptions = {
                args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
                executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
                headless: true,
                timeout: 120000,
            };
        } else {
            launchOptions = {
                args: c.args,
                defaultViewport: c.defaultViewport,
                executablePath: await c.executablePath(),
                headless: c.headless,
                timeout: 120000,
            };
        }

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        browser = await puppeteer.launch(launchOptions as any);
        const page = await browser.newPage();
        await page.setDefaultNavigationTimeout(120000);
        await page.setDefaultTimeout(120000);

        await page.setContent(html, { waitUntil: 'networkidle0' });

        // Optional: wait a tiny bit more for layout stabilization
        await new Promise(r => setTimeout(r, 500));

        if (showWatermark) {
            await injectWatermark(page);
        }

        const pdfBuffer = await page.pdf({
            format: 'A4',
            printBackground: true,
            margin: { top: 0, right: 0, bottom: 0, left: 0 }, // Template handles its own margins
            preferCSSPageSize: true
        });

        if (!pdfBuffer || pdfBuffer.length === 0) {
            throw new Error('PDF generation produced an empty buffer');
        }

        // Fire-and-forget: Admin Log & Usage Increment
        if (session?.userId) {
            logPDFDownload({
                userId: session.userId,
                resumeName: resumeData?.name || 'Untitled',
                template,
                watermarked: showWatermark
            });
            // Also increment free usage count
            incrementForgeUsage('resumeforge').catch(e => console.error('[Download] Usage increment failed:', e));
        }

        console.log('[Download] PDF generation successful, returning response...');

        return new NextResponse(Buffer.from(pdfBuffer), {
            status: 200,
            headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': 'attachment; filename="resume.pdf"',
                'X-Watermark': showWatermark ? 'true' : 'false',
                'Cache-Control': 'no-store, max-age=0',
            },
        });

    } catch (e: unknown) {
        const err = e as Error;
        console.error('[Download] CRITICAL Error:', err);
        const errorDetail = {
            error: 'PDF generation failed',
            details: err.message || String(err),
            stack: err.stack
        };

        try {
            const logsDir = path.join(process.cwd(), 'tmp');
            if (!fs.existsSync(logsDir)) fs.mkdirSync(logsDir, { recursive: true });
            fs.writeFileSync(path.join(logsDir, 'pdf_download_error.json'), JSON.stringify(errorDetail, null, 2));
        } catch { }

        return NextResponse.json(errorDetail, { status: 500 });
    } finally {
        if (browser) await browser.close();
    }
}



