import React from 'react';
import { ResumeData } from '@/types/resume';
import { cleanBullet } from '@/templates/utils';

interface Props {
    resumeData: ResumeData;
    isWatermarked?: boolean;
}

export const HarvardPreview: React.FC<Props> = ({ resumeData: r, isWatermarked }) => {
    const buildLocationLine = (r: ResumeData) => {
        const parts = [r.location, r.country].filter(Boolean);
        return parts.join(', ');
    };

    const buildContactLine = (r: ResumeData, sep: string) => {
        const parts = [
            r.email,
            r.phone,
            r.linkedin && <a key="li" href={r.linkedin} className="hover:underline">LinkedIn</a>,
            r.github && <a key="gh" href={r.github} className="hover:underline">GitHub</a>,
        ].filter(Boolean);

        return parts.reduce((prev: React.ReactNode[], curr, i) => {
            if (i > 0) prev.push(<span key={`s${i}`} className="mx-1">{sep}</span>);
            prev.push(curr as React.ReactNode);
            return prev;
        }, []);
    };

    const locationLine = buildLocationLine(r);

    return (
        <div className="bg-white text-black p-[20mm] mx-auto shadow-2xl relative" 
            style={{ 
                width: '210mm', 
                minHeight: '297mm', 
                fontFamily: 'Georgia, "Times New Roman", serif',
                fontSize: '11pt',
                lineHeight: '1.25'
            }}>
            {isWatermarked && (
                <div className="absolute inset-0 pointer-events-none overflow-hidden z-10 opacity-[0.05]">
                    {Array.from({ length: 100 }).map((_, i) => (
                        <div key={i} className="absolute whitespace-nowrap font-bold text-[13px] rotate-[-35deg]"
                            style={{ 
                                top: `${Math.floor(i / 5) * 160 + (i % 5) * 50}px`,
                                left: `${(i % 5) * 320 - 80}px`,
                            }}>
                            Generated by ResumeForgeAI – Upgrade to remove watermark
                        </div>
                    ))}
                </div>
            )}

            <div className="text-center mb-[11px]">
                <h1 className="text-[22pt] font-bold mb-1 tracking-[0.3px] uppercase">{r.name}</h1>
                <div className="text-[9pt] text-gray-800">
                    {locationLine && <div>{locationLine}</div>}
                    <div>{buildContactLine(r, ' \u2022 ')}</div>
                </div>
            </div>

            {r.summary && (
                <section className="mb-[9px]">
                    <h2 className="text-[10pt] font-bold uppercase tracking-[1.2px] border-b-[1.5px] border-black pb-0.5 mb-[5px]">Summary</h2>
                    <p className="text-[10.5pt] leading-[1.3]">{r.summary}</p>
                </section>
            )}

            {(r.skillCategories?.length || r.skills?.length) && (
                <section className="mb-[9px]">
                    <h2 className="text-[10pt] font-bold uppercase tracking-[1.2px] border-b-[1.5px] border-black pb-0.5 mb-[5px]">Technical Skills</h2>
                    <div className="text-[9.8pt] space-y-0.5">
                        {r.skillCategories ? r.skillCategories.map((cat, i) => (
                            <div key={i}><span className="font-bold">{cat.category}:</span> {cat.skills.join(', ')}</div>
                        )) : (
                            <div>{r.skills.join(', ')}</div>
                        )}
                    </div>
                </section>
            )}

            {r.experience?.length > 0 && (
                <section className="mb-[9px]">
                    <h2 className="text-[10pt] font-bold uppercase tracking-[1.2px] border-b-[1.5px] border-black pb-0.5 mb-[5px]">Experience</h2>
                    {r.experience.map((exp, i) => (
                        <div key={i} className="mb-2">
                            <div className="flex justify-between items-baseline gap-2">
                                <span className="font-bold text-[11pt]">{exp.role}, {exp.company}</span>
                                <span className="text-[9pt] whitespace-nowrap">{exp.duration}</span>
                            </div>
                            <ul className="ml-5 mt-0.5 list-disc space-y-0.5">
                                {exp.points.filter(Boolean).map((p, j) => (
                                    <li key={j} className="text-[10.5pt]">{cleanBullet(p)}</li>
                                ))}
                            </ul>
                        </div>
                    ))}
                </section>
            )}

            {r.projects?.length > 0 && (
                <section className="mb-[9px]">
                    <h2 className="text-[10pt] font-bold uppercase tracking-[1.2px] border-b-[1.5px] border-black pb-0.5 mb-[5px]">Projects</h2>
                    {r.projects.map((p, i) => (
                        <div key={i} className="mb-2">
                            <div className="flex justify-between items-baseline gap-2">
                                <span className="font-bold text-[11pt]">{p.title}</span>
                                <span className="text-[9pt] whitespace-nowrap">{p.tech.slice(0, 5).join(', ')}</span>
                            </div>
                            {(p.liveLink || p.githubLink) && (
                                <div className="text-[8.5pt] italic text-gray-700 mb-0.5 line-clamp-1">
                                    {[p.liveLink && `Live: ${p.liveLink}`, p.githubLink && `GitHub: ${p.githubLink}`].filter(Boolean).join(' | ')}
                                </div>
                            )}
                            <ul className="ml-5 mt-0.5 list-disc space-y-0.5">
                                {p.description.filter(Boolean).map((d, j) => (
                                    <li key={j} className="text-[10.5pt]">{cleanBullet(d)}</li>
                                ))}
                            </ul>
                        </div>
                    ))}
                </section>
            )}

            {r.certifications && r.certifications.length > 0 && (
                <section className="mb-[9px]">
                    <h2 className="text-[10pt] font-bold uppercase tracking-[1.2px] border-b-[1.5px] border-black pb-0.5 mb-[5px]">Certifications</h2>
                    <div className="text-[9.8pt] space-y-0.5">
                        {r.certifications.map((c, i) => (
                            <div key={i}><span className="font-bold">{c.title}</span> \u2014 {c.issuer} ({c.year})</div>
                        ))}
                    </div>
                </section>
            )}

            {r.education?.length > 0 && (
                <section className="mb-[9px]">
                    <h2 className="text-[10pt] font-bold uppercase tracking-[1.2px] border-b-[1.5px] border-black pb-0.5 mb-[5px]">Education</h2>
                    {r.education.map((edu, i) => (
                        <div key={i} className="mb-2">
                            <div className="flex justify-between items-baseline gap-2">
                                <span className="font-bold text-[11pt]">{edu.school}</span>
                                <span className="text-[9pt] whitespace-nowrap">{edu.duration}</span>
                            </div>
                            <div className="italic text-[9.5pt]">{edu.degree}{edu.cgpa ? ` \u2014 CGPA: ${edu.cgpa}` : ''}</div>
                        </div>
                    ))}
                </section>
            )}
        </div>
    );
};
