import Link from 'next/link';

export const metadata = { title: 'Terms & Conditions — ResumeForge' };

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-[#070710] text-slate-200 py-16 px-6">
            <div className="max-w-3xl mx-auto">
                <Link href="/signup" className="text-purple-400 hover:text-purple-300 text-sm mb-8 inline-block">← Back to Sign Up</Link>

                <h1 className="text-4xl font-bold mb-2">Terms &amp; Conditions</h1>
                <p className="text-slate-500 text-sm mb-10">Last updated: February 2026</p>

                <div className="prose prose-invert prose-slate max-w-none space-y-8 text-slate-300 leading-relaxed">

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
                        <p>By accessing or using ResumeForge, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you may not use our service.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">2. Use of Service</h2>
                        <p>ResumeForge provides an AI-powered resume builder. You agree to:</p>
                        <ul className="list-disc list-inside space-y-2 mt-2 text-slate-400">
                            <li>Use the service only for lawful purposes.</li>
                            <li>Not upload content that violates third-party rights.</li>
                            <li>Not attempt to reverse-engineer or exploit the platform.</li>
                            <li>Provide accurate information when creating an account.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">3. Account Responsibility</h2>
                        <p>You are responsible for maintaining the security of your account credentials. ResumeForge is not liable for any loss resulting from unauthorised access to your account.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">4. Intellectual Property</h2>
                        <p>All platform content, design, and code remain the property of ResumeForge. Resumes you generate are your own — we claim no ownership over your personal data or resume content.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">5. AI-Generated Content</h2>
                        <p>Resume content generated by our AI tools is provided as a starting point. You are solely responsible for reviewing, editing, and verifying the accuracy of any AI-generated content before submitting it to employers.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">6. Limitation of Liability</h2>
                        <p>ResumeForge is provided &quot;as is&quot; without warranties of any kind. We are not liable for any direct, indirect, or incidental damages arising from use of the service, employment decisions made by third parties, or accuracy of AI-generated content.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">7. Termination</h2>
                        <p>We reserve the right to suspend or terminate accounts that violate these terms, engage in abusive behaviour, or misuse the platform.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">8. Changes to Terms</h2>
                        <p>We may update these terms at any time. Continued use of the service after changes constitutes acceptance of the updated terms.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">9. Contact</h2>
                        <p>For questions about these terms, contact us at: <span className="text-purple-400">support@resumeforge.ai</span></p>
                    </section>
                </div>
            </div>
        </div>
    );
}
